### ISSUE TITLE
[Feature] Multiple cookies

### ISSUE THREAD

**Issue by aeq-dev** [pdazcom/laravel-referrals#12]
Hi,

Thank you for this awesome package,
Please could you add this TODO: store cookies in array so multiple cookies at the same time are possible as mentioned here [Laravel-Referrals](https://blog.damirmiladinov.com/laravel/building-laravel-referral-system.html#.Wc4eA6xJaHo)

Thanks

**Comment by pdazcom** [comment]
Hi, 
thanks for your interest in my package. I will try to find time to implement this functionality as soon as possible.

**Comment by aeq-dev** [comment]
Thank you :)
